Add licensing info, bump version to 2.0.4, fix exits

diff --git a/swig.SlackBuild b/swig.SlackBuild
--- a/swig.SlackBuild
+++ b/swig.SlackBuild
@@ -1,14 +1,31 @@
 #!/bin/sh
 #
-# SlackBuild for swig
-# Written by Georgi D. Sotirov <gdsotirov@dir.bg>
+# Slackware build script for SWIG
+# Copyright (C) 2006,2008-2011 Georgi D. Sotirov <gdsotirov@dir.bg>
+#
+# This program is free software; you can redistribute it and/or
+# modify it under the terms of the GNU General Public License
+# as published by the Free Software Foundation; either version 2
+# of the License, or (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+# 
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, write to the Free Software
+# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
+#
 # Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
+# $Id: swig.SlackBuild,v 1.7 2011/12/11 10:47:25 gsotirov Exp $
+#
 
-. ../slack-package.conf
+. ../../slack-package.conf
 
 NAME=swig
-VERSION=2.0.0
+VERSION=2.0.4
 BUILD=${BUILD:-1}
 
 TMP=${TMP:-/tmp}
@@ -33,7 +50,7 @@ mkdir -p $PKG
 
 # Extract the source
 cd $TMP
-tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 1
+tar -xvf $CWD/$NAME-$VERSION.tar.gz || exit 3
 cd $SRC
 fix_source
 
@@ -42,11 +59,11 @@ CFLAGS=$SLKCFLAGS \
 CXXFLAGS=$SLKCFLAGS \
 ./configure --build=$ARCH-slackware-linux \
             --prefix=/usr \
-            --mandir=/usr/man || exit 1
+            --mandir=/usr/man || exit 4
 
 # Build & install
-make -j4 || exit 2
-make DESTDIR=$PKG install || exit 3
+make -j4 || exit 5
+make DESTDIR=$PKG install || exit 6
 
 # Prepare
 bin_perms $PKG
@@ -65,6 +82,7 @@ install -m 644 $CWD/slack-required   $PKG/usr/src/slackbuilds/$NAME-$VERSION/sla
 install -m 644 $CWD/slack-suggests   $PKG/usr/src/slackbuilds/$NAME-$VERSION/slack-suggests
 install -m 644 $CWD/$NAME.SlackBuild $PKG/usr/src/slackbuilds/$NAME-$VERSION/$NAME.SlackBuild
 
+# Assemble
 cd $PKG
 PKGNAME=$NAME-$VERSION-$ARCH-$BUILD$MYIN
 makepkg -l y -c n $PKG_DIR/$PKGNAME.txz
@@ -72,6 +90,7 @@ cd $PKG_DIR
 md5sum $PKGNAME.txz > $PKGNAME.txz.md5
 cat $PKG/install/slack-desc > $PKG_DIR/$PKGNAME.txt
 
+# Clean up
 if [ "$1" == "--cleanup" ]; then
   rm -r $SRC
   rm -r $PKG
